### ISSUE TITLE
IS-IS Topology Tree Diagram

### ISSUE THREAD

**Issue by OlgaHuawei** [oscargdd/drafts-nmop-isis-ospf-topologies#5]
Is the IS-IS Topology Tree Diagram version aligned with the version of the module afterwards. Examples:
- Link is missing
- Is it intentional that we have tp attributes for both TP and Link? Mismatch between the tree and module
 
 augment "/nw:networks/nw:network/nt:link/l3t:l3-link-attributes" {
    when "/nw:networks/nw:network/nw:network-types/isisnt:isis-topology" {
      description
        "Augmentation parameters apply only for networks with
        IS-IS topology";
    }
    description
      "Augments topology link configuration";
    uses isis-termination-point-attributes;
  }

**Comment by bclaise** [comment]
I incorported the latest YANG tree, as of today, based on the YANG module in the .md file

**Comment by oscargdd** [comment]
FIXED
